// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  buttonColorYellow: string;
  buttonSizeSmall: string;
  buttonWidthFullwidth: string;
  root: string;
}
export const cssExports: CssExports;
export default cssExports;
