// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  menuLink: string;
  menuWrapper: string;
  pokemonLogo: string;
  root: string;
  wrapper: string;
}
export const cssExports: CssExports;
export default cssExports;
